### PR TITLE
RDKBDEV-2326 Updating platform_hal.h file to add API for Eco Mode status

### PR DESCRIPTION
**Pull request by biju-vi**
RDKBDEV-2326 Updating platform_hal.h file to add API for Eco Mode status

### CODE REVIEW

**Review by johnsonsebastiar — APPROVED** [review]
New API addition looks to be good and is within the feature flag so that it doesn't affect any other platform.

**Review by johnsonsebastiar — APPROVED** [review]

**Comment by GoutamD2905** [comment]
@johnsonsebastiar @sbarre01 @DouglasAdler  we should have tag version for every release into main. what is tag version here for addition of this new API ?

**Review by GoutamD2905 — COMMENTED** [review]
@johnsonsebastiar @sbarre01 @DouglasAdler we should have tag version for every release into main. what is tag version here for addition of this new API ?

WIth new tag version of main release ( commit id ) which should be used in repective interface recipe in gerrit to get reflect of the new API.

CC : @Ulrond

**Comment by biju-vi** [comment]
@GoutamD2905 , new tag version 1.2.0 is for this commit id . Could you please check ?
git show 1.2.0
commit 47e8c9d9e2e126d563b4e2d74a590e6526391685 (HEAD -> main, tag: 1.2.0, origin/main, origin/HEAD)
Merge: 40c4c91 b886d3f
Author: Stephen Barrett <sbarre01@users.noreply.github.com>
Date:   Thu Dec 28 19:56:14 2023 +0000

    Merge pull request #7 from biju-vi/main

**Pull request merged**
